name: Notify Parent Repo

on:
  push:
    branches: [ "main" ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger parent repo deployment
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PARENT_REPO_TOKEN }}" \
            https://api.github.com/repos/rxluk/mindrabar-api/dispatches \
            -d '{"event_type":"frontend-updated"}'
